
---
server:
  port: 8080

spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

    hibernate:
      ddl-auto: create

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    master:
      jdbc-url: jdbc:mysql://localhost:3309/qtome
      username: root
      password: root
    slave1:
      jdbc-url: jdbc:mysql://localhost:3309/qtome
      username: root
      password: root
    slave2:
      jdbc-url: jdbc:mysql://localhost:3309/qtome
      username: root
      password: root

springdoc:
  swagger-ui:
    url: /docs/SAMPLE - 0.0.1.json
    path: /docs/swagger

slack:
  webhook: https://hooks.slack.com/services/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