
---
server:
  port: 8080

spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: create
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

springdoc:
  swagger-ui:
    url: /docs/SAMPLE - 0.0.1.json
    path: /docs/swagger

