
---
server:
  port: 8080

spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQL8Dialect

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    master:
      url: jdbc:mysql://localhost:3309/qtome
      username: root
      password: root
    slave1:
      url: jdbc:mysql://localhost:3309/qtome
      username: root
      password: root
    slave2:
      url: jdbc:mysql://localhost:3309/qtome
      username: root
      password: root

springdoc:
  swagger-ui:
    url: /docs/SAMPLE - 0.0.1.json
    path: /docs/swagger

